from voice_auth_engine.audio_preprocessor import (
    AudioData,
    AudioDecodeError,
    AudioInput,
    AudioPreprocessError,
    decode_audio,
    load_audio,
)
from voice_auth_engine.audio_validator import (
    DEFAULT_MIN_SPEECH_SECONDS,
    SUPPORTED_EXTENSIONS,
    AudioValidationError,
    EmptyAudioError,
    InsufficientDurationError,
    UnsupportedExtensionError,
    validate_audio,
    validate_extension,
)
from voice_auth_engine.embedding_extractor import (
    Embedding,
    EmbeddingExtractionError,
    EmbeddingExtractorError,
    EmbeddingModelLoadError,
    extract_embedding,
)
from voice_auth_engine.math import cosine_similarity
from voice_auth_engine.passphrase_auth import (
    PassphraseAuth,
    PassphraseAuthEnroller,
    PassphraseAuthError,
    PassphraseAuthVerifier,
)
from voice_auth_engine.passphrase_validator import (
    EmptyPassphraseError,
    InsufficientPhonemeError,
    PassphraseInfo,
    PassphraseValidationError,
    analyze_passphrase,
    validate_passphrase,
)
from voice_auth_engine.speech_detector import (
    SpeechDetectorError,
    SpeechDetectorModelLoadError,
    SpeechSegment,
    SpeechSegments,
    detect_speech,
    extract_speech,
)
from voice_auth_engine.speech_recognizer import (
    RecognitionError,
    RecognizerModelLoadError,
    SpeechRecognizerError,
    TranscriptionResult,
    transcribe,
)

__all__ = [
    "AudioData",
    "AudioDecodeError",
    "AudioInput",
    "AudioPreprocessError",
    "AudioValidationError",
    "DEFAULT_MIN_SPEECH_SECONDS",
    "Embedding",
    "EmbeddingExtractionError",
    "EmbeddingExtractorError",
    "EmbeddingModelLoadError",
    "EmptyAudioError",
    "EmptyPassphraseError",
    "InsufficientDurationError",
    "InsufficientPhonemeError",
    "PassphraseAuth",
    "PassphraseAuthError",
    "PassphraseAuthEnroller",
    "PassphraseAuthVerifier",
    "PassphraseInfo",
    "PassphraseValidationError",
    "RecognitionError",
    "RecognizerModelLoadError",
    "SpeechDetectorError",
    "SpeechDetectorModelLoadError",
    "SpeechRecognizerError",
    "SpeechSegment",
    "SpeechSegments",
    "SUPPORTED_EXTENSIONS",
    "TranscriptionResult",
    "UnsupportedExtensionError",
    "analyze_passphrase",
    "cosine_similarity",
    "detect_speech",
    "extract_embedding",
    "extract_speech",
    "load_audio",
    "decode_audio",
    "transcribe",
    "validate_audio",
    "validate_extension",
    "validate_passphrase",
]
