from voice_auth_engine.audio_preprocessor import (
    AudioData,
    AudioDecodeError,
    AudioPreprocessError,
    decode_audio,
    load_audio,
)
from voice_auth_engine.audio_validator import (
    DEFAULT_MIN_SPEECH_SECONDS,
    SUPPORTED_EXTENSIONS,
    AudioValidationError,
    EmptyAudioError,
    InsufficientDurationError,
    UnsupportedExtensionError,
    validate_audio,
    validate_extension,
)
from voice_auth_engine.embedding_extractor import (
    Embedding,
    EmbeddingExtractionError,
    EmbeddingExtractorError,
    EmbeddingModelLoadError,
    extract_embedding,
)
from voice_auth_engine.math import cosine_similarity
from voice_auth_engine.passphrase_validator import (
    EmptyPassphraseError,
    InsufficientPhonemeError,
    PassphraseInfo,
    PassphraseValidationError,
    analyze_passphrase,
    validate_passphrase,
)
from voice_auth_engine.passphrase_verifier import (
    InsufficientSpeechError,
    PassphraseEnroller,
    PassphraseVerifier,
    PassphraseVerifierError,
    VerificationResult,
    check_speech_duration,
)
from voice_auth_engine.speech_detector import (
    SpeechDetectorError,
    SpeechDetectorModelLoadError,
    SpeechSegment,
    SpeechSegments,
    detect_speech,
    extract_speech,
)
from voice_auth_engine.speech_recognizer import (
    RecognitionError,
    RecognizerModelLoadError,
    SpeechRecognizerError,
    TranscriptionResult,
    transcribe,
)

__all__ = [
    "AudioData",
    "AudioDecodeError",
    "AudioPreprocessError",
    "AudioValidationError",
    "DEFAULT_MIN_SPEECH_SECONDS",
    "Embedding",
    "EmbeddingExtractionError",
    "EmbeddingExtractorError",
    "EmbeddingModelLoadError",
    "EmptyAudioError",
    "EmptyPassphraseError",
    "InsufficientDurationError",
    "InsufficientPhonemeError",
    "InsufficientSpeechError",
    "PassphraseInfo",
    "PassphraseValidationError",
    "RecognitionError",
    "RecognizerModelLoadError",
    "PassphraseEnroller",
    "PassphraseVerifier",
    "PassphraseVerifierError",
    "SpeechDetectorError",
    "SpeechDetectorModelLoadError",
    "SpeechRecognizerError",
    "SpeechSegment",
    "SpeechSegments",
    "SUPPORTED_EXTENSIONS",
    "TranscriptionResult",
    "UnsupportedExtensionError",
    "VerificationResult",
    "analyze_passphrase",
    "check_speech_duration",
    "cosine_similarity",
    "detect_speech",
    "extract_embedding",
    "extract_speech",
    "load_audio",
    "decode_audio",
    "transcribe",
    "validate_audio",
    "validate_extension",
    "validate_passphrase",
]
